[webservers]
web-1 ansible_host=51.250.4.5 fqdn=fhmvh1o7e9eo9bu0pvpb.auto.internal
web-2 ansible_host=93.77.186.51 fqdn=fhmujomqkjefhpsdl1dk.auto.internal

[databases]
main ansible_host=111.88.241.60 fqdn=fhmlkqufveblauchi1im.auto.internal
replica ansible_host=111.88.253.34 fqdn=fhmnlo22i2tn5supncgk.auto.internal

[storage]
storage ansible_host=111.88.245.207 fqdn=fhmu4o1h9fivfl5ad575.auto.internal
